import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Nav from '../components/Nav'


export default function Home() {
  return (
    <div >
      <Head>
        <title>HULU 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


<Header />  
<Nav />
{/* nav  */}
{/* results */}

    </div>
  )
}
